/* Automatically generated by './build/bin/build-entry.js' */

import Breadcrumb from '../packages/breadcrumb/index.js';
import Card from '../packages/card/index.js';
import Item from '../packages/item/index.js';
import Swiper from '../packages/swiper/index.js';
import Switch from '../packages/switch/index.js';
import Title from '../packages/title/index.js';
import Tooltip from '../packages/tooltip/index.js';
import locale from 'composite-ui/src/locale';

const components = [
  Breadcrumb,
  Card,
  Item,
  Swiper,
  Switch,
  Title,
  Tooltip,
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });


  Vue.prototype.$COMPOSITE = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Breadcrumb,
  Card,
  Item,
  Swiper,
  Switch,
  Title,
  Tooltip
};
